### PR TITLE
fix position value

### PR DESCRIPTION
**Pull request by DanielRuf**
## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by TotomInc** [comment]
Can you explain why you have done this change? Do you have a screenshot? Thanks!

**Comment by DanielRuf** [comment]
@TotomInc The previous value is not a valid property value of `position`. Position only allows `fixed`, `absolute`, `sticky`, `relative` and so on.

Chrome will show you that this is not a valid value.

**Comment by DanielRuf** [comment]
bildschirmfoto 2017-11-22 um 09 13 20

**Comment by TotomInc** [comment]
My bad, I haven't seen it was a wrong value.

**Comment by rhyneav** [comment]
Nice catch, thank you for the fix!

**Comment by DanielRuf** [comment]
You are welcome!

**Pull request merged**
