### PR TITLE
Update buttons.less

### PR DESCRIPTION
**Pull request by Nilanno**
Button click state for issue #63

### CODE REVIEW

**Comment by TotomInc** [comment]
I tried the demo but it looks like nothing change when I click or add `:active` to a button. Did it works for you?

**Comment by afzalsayed96** [comment]
Could you provide some more details and screenshots if possible in your pull request?

**Comment by Nilanno** [comment]
@TotomInc sorry, I really forgot 'and' sign before pseudoclass :)

Images of button state while on click action before commit, and after commit.

image
image

**Comment by Fraham** [comment]
@Nilanno have you checked the develop branch? I think click animation has already been added on the develop branch

**Comment by Fraham** [comment]
See #17

**Comment by Nilanno** [comment]
@Fraham yes, I checked.
It seems like default buttons do not have this feature.
Try to click on button here https://www.getpapercss.com/#buttons

**Comment by afzalsayed96** [comment]
Great! I see the difference. Is there a way to disable this feature if a user doesn't want the effect?

**Comment by Nilanno** [comment]
I'm pretty sure this feature should be a general behavior, as in browsers by default, for accessibility.

**Comment by rhyneav** [comment]
Here's a gif for anyone who needs it
preview

And I agree that it should be a default feature. I like the feedback of knowing the button was clicked.

I don't know if this is technically a patch though. Could you please update the base branch to develop? This would be perfect to add in v1.2.

**Comment by TotomInc** [comment]
It looks really cool, it was an important feature IMO in terms of UX. Thanks for your contribution @Nilanno

**Comment by Nilanno** [comment]
Updated base branch to develop

**Comment by rhyneav** [comment]
Thank you @Nilanno! It looks like all buttons now have an effect when clicked. This fits well with @Fraham's click styles too.

**Pull request merged**
