### PR TITLE
Modify shadow hover behaviour

### PR DESCRIPTION
**Pull request by maciejmatu**
## Brief description
Add transforms to hovered elements with shadow.
Fix `:hover` selector duplication.
Move repeated shadow values and colors to variables.

## Developer Certificate of Origin
- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures
buttons

## Further details
I thought that those buttons need a little more life in them 😉. Maybe you'll like it too. Also, when it comes to duplicated :hover selector, you can see it in chrome devtools. The hovered buttons will have `.paper-btn:hover:hover` selector. It behaves like that, because you included `.shadow-hover` class inside `:hover` selector for element, but this class also has `:hover` selector inside itself. I checked if my change didn't break anything and it seems like it's all good.

### CODE REVIEW

**Comment by rhyneav** [comment]
Oh that is so smooth, and it definitely adds some life to the hover. I love it!

Also, thank you for cleaning up my mess with the `hover` and DRYing up the shadow styles :)

**Comment by rhyneav** [comment]
One quick thing, could you please change the base branch from `master` to `develop`? This is just to keep the docs consistent with the current release. The develop branch will eventually merge into master as version 1.2 

Thanks again @maciejmatu!

**Comment by maciejmatu** [comment]
Done. There is a conflict, which I cannot resolve (don't know why). Anyway, I really like how you achieved those borders. Thinking out of the box 😄. Great work!

**Comment by rhyneav** [comment]
Awesome, thank you! Really like the fresh new button hover you added!

**Pull request merged**
