### PR TITLE
Pull request template to get DCO (Developers Certificate of Origin)

### PR DESCRIPTION
**Pull request by brodybits**
Checkbox to get DCO for each contribution

Some links for reference:
- <https://developercertificate.org/>
- <https://oss.kemitchell.com/#contribution-management>
- <https://github.com/choojs/discuss/issues/3>, with some additional resources
- <https://lwn.net/Articles/592503/>

### CODE REVIEW

**Comment by rhyneav** [comment]
Cool! So this is basically a CYA type of thing for pull requests?

**Comment by brodybits** [comment]
You could say that - CYA and make it a little more professional.

I just updated with headers for the contributor to fill in "Sample pictures" and "Further details" sections.

Still based on master, hoping to see it integrated soon:)

**Comment by rhyneav** [comment]
I like it! Since it doesn't touch any of the CSS, I'll go ahead and merge it into master so it can be used now :)

**Comment by brodybits** [comment]
Thanks!

**Pull request merged**
