### PR TITLE
Fix for overflow x-axis in mobile view

### PR DESCRIPTION
**Pull request by afzalsayed96**
## Brief description

The x-axis overflow issue #52 is fixed in this commit

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures (Firefox)

image

image

image

## Further details

Added media query for reduced padding in mobile for table and separated paper div from container

### CODE REVIEW

**Comment by rhyneav** [comment]
Awesome! Could you also please update the get started snippets in the index.html and readme to reflect this change?

**Comment by rhyneav** [comment]
This is perfect, thank you! 

Last thing, just to save some headache all around, could you update the base branch to develop? While this is a patch, I'd like to just include it with v1.2 as that will be released soon. This will likely be the last addition to the develop branch before that is split off into the v1.2 branch.

**Comment by afzalsayed96** [comment]
Great done changing the base

**Comment by rhyneav** [comment]
You rock, thank you!

**Pull request merged**
