### PR TITLE
Added a basic .editorconfig

### PR DESCRIPTION
**Pull request by TotomInc**
## Brief description

As #54 says, we need an `.editorconfig` file because everyone is using its own indentation size and type, add/remove EOL in files. To make sure these changes are effective, use an `editorconfig` plugin/addon on your IDE. For example in Atom there is the [editorconfig package](https://atom.io/packages/editorconfig), as well for [Sublime](https://github.com/sindresorhus/editorconfig-sublime), [VS Code](https://github.com/editorconfig/editorconfig-vscode), [Vim](https://github.com/editorconfig/editorconfig-vim), ...

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by rhyneav** [comment]
This is perfect @TotomInc, thank you for the addition. Do you think it would be helpful to include anything in the readme? Maybe just a copy/paste of the description of this PR.

And could you please make the base of this the master branch? I think this would add value immediately rather than waiting for the next release.

**Comment by TotomInc** [comment]
I think we should add the few lines about how to properly implement a .editorconfig with the specific plugins/add-ons.

**Comment by TotomInc** [comment]
I think it's better to point to develop instead of master in terms of conflicts, it's more coherent also to keep merging to develop.

**Comment by rhyneav** [comment]
That makes sense about merging to develop. I'll cool it off with merging to master so often :)

And most IDEs should pick up the .editorconfig automatically, right?

**Comment by TotomInc** [comment]
Well, not all IDEs natively support editorconfig files, especially when it's a pretty basic code-editor such as Sublime or Vim, there are a lot of people using them. I've also added a few lines about the editorconfig file and how to properly integrate it in the IDE.

**Comment by rhyneav** [comment]
Perfect, thank you!

**Pull request merged**
