### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by afzalsayed96**
## Brief description

Adding a code of conduct

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Further details

https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

### CODE REVIEW

**Comment by rhyneav** [comment]
Everyone in this community has been wonderful, but adding this would be great. Is this pretty much the boilerplate code of conduct for open source projects?

**Comment by afzalsayed96** [comment]
Hell yes! the community has been amazing so far and I loved the experience here. But no doubt it is needed in the long run.
This was provided ready-made by GitHub suitable for projects of all sizes. We can further customize it to our specific needs. Also do you have an email address like admin@getpapercss.com or would you like to add your personal email as a contact person?

**Comment by rhyneav** [comment]
Sounds great! I created getpapercss@gmail.com that might be good for this. Just to keep things a little more separate from the personal email :)

**Comment by rhyneav** [comment]
Perfect, thank you!

**Pull request merged**
