### PR TITLE
Add IDs to inputs and selects

### PR DESCRIPTION
**Pull request by valerymelou**
## Brief description
Add IDs to inputs and selects and reference them in their respective labels.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Afaik you only need the name, not an ID.

**Comment by Kaperskyguru** [comment]
please can u drop a screenshot of this changes

**Comment by DanielRuf** [comment]
> please can u drop a screenshot of this changes

There are no visual changes. Why do you always ask for screenshots?

**Comment by DanielRuf** [comment]
See https://github.com/rhyneav/papercss/pull/58/files

**Comment by valerymelou** [comment]
They just allow focusing inputs and selects in the doc by clicking on their label. Should I make a screenshot of that?

**Comment by rhyneav** [comment]
Very needed, thank you for this update!

**Pull request merged**
