### PR TITLE
Feature short popover attributes

### PR DESCRIPTION
**Pull request by wintercounter**
## Brief description
I merged the position attribute into the popover attribute, achieving the same results using only 1 attribute instead of 2. Updated demo as well.
...

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Further details
If there are plans the extend popover features further (more attributes) then this is not a good solution. In case the plan is to keep it as simple as it is now, it's viable.
...

### CODE REVIEW

**Comment by rhyneav** [comment]
Awesome, and thank you for the PR!

I'm personally a big fan of keeping things concise, but my two concerns are: 
1. The new style is a little hard to read with the lighter background color. 
image. 
2. If someone were currently using popovers, they would have to refactor if they upgraded versions after the next release. Not a big deal by any means, just something to consider.

@TotomInc originally added this feature, so I'd like to hear his thoughts too!

**Comment by wintercounter** [comment]
The color changes are not from my side, it was in the `develop` branch. Sure, it's a breaking change, it should be included in 2.0.0.

**Comment by TotomInc** [comment]
Thanks for your contribution @wintercounter, I wanted to improve the popovers recently but I was quite short on time. It's a nice idea to keep things consice, as it's the goal of PaperCSS.

However I agree with @rhyneav, text is a bit harder to read on a lighter background, is it possible to revert to the old one? On a side note, what about a small arrow on the bottom of the tooltip, what are your thoughts on this?

About this "breaking change" on the popovers, we should look at the way we ship new versions. This means: should we wait before shipping a new version, until we reach a milestone?

**Comment by wintercounter** [comment]
Yeah, definitely should wait for a mayor release. Let me check the colors, maybe I screwed something there.

**Comment by TotomInc** [comment]
Did we have a light-dark variable color? If not you could create one and assign it to popovers background.

**Comment by rhyneav** [comment]
Nice catch on the `@white-dark` change! Thank you for updating that too. I'm with @TotomInc, everything looks great!

**Pull request merged**
