### PR TITLE
More button styles

### PR DESCRIPTION
**Pull request by Fraham**
Added the standard colour options to button and also included click transition for when the user clicks on the button

capture

### CODE REVIEW

**Comment by rhyneav** [comment]
Absolutely love it, it looks great! The click effect is a nice touch too.

Also, when I merged in #13 it created a conflict in the colors.less file. Could you please resolve that file, and I'll get this merged in shortly thereafter.

I also really like the functions you've been creating to generate colors. That's definitely something I need to work on more myself :)

**Comment by Fraham** [comment]
Conflict resolved

**Comment by rhyneav** [comment]
Awesome, thank you! One very last thing: when you added the background color transition, it removed the shadow transition for hover so it's no longer smooth. If you could please add this back in, we should be good to rock and roll!

**Comment by Fraham** [comment]
Issue fixed

**Comment by rhyneav** [comment]
Thank you again, these look great!

**Pull request merged**
