### PR TITLE
Change the display of focused buttons

### PR DESCRIPTION
**Pull request by valerymelou**
## Brief description

This will visually update the display of focused buttons so that users
using a keyboard will differenciate them from other buttons.

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

screenshot from 2017-11-24 08-35-04

## Further details

You'll notice that I manually copied styles of `.shadow-hover`. I tried
```
&:focus{
    border: 2px solid @secondary;
    .shadow-hover;
}
```
without success.

### CODE REVIEW

**Comment by rhyneav** [comment]
This is a nice touch! Definitely helps with accessibility. Do you think it might be beneficial to add a change in border style to the color buttons as well? Just to keep things consistent with the default buttons. Possibly make the border darker rather than changing to blue?

buttons

buttons-color

**Comment by valerymelou** [comment]
I completely forgot about those other buttons. I think it might be best to apply the same effect of hover on focused buttons.

**Comment by TotomInc** [comment]
IMO, the blue color is good for focus, while dark/white is good for hover/active @rhyneav . It looks really great @valerymelou .

**Comment by rhyneav** [comment]
So the blue border would also appear on the other button styles when they are focused? I like it! The only issue might be with the secondary button styles, but I don't think it's a big problem since the focus also depresses it.

**Comment by TotomInc** [comment]
Problem solved @rhyneav ! Let's merge it? Code looks okay.

**Comment by rhyneav** [comment]
Sounds good, merged!

**Pull request merged**
